# Generated by Django 4.0.4 on 2022-04-22 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUUIDModel',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_uuids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
