# Generated by Django 4.0.4 on 2022-04-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customeruuidmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruuidmodel',
            name='customer_id',
            field=models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
