# Generated by Django 4.0.4 on 2022-04-22 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customeruuidmodel_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerID',
            fields=[
                ('customer_id', models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_uuids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerUUIDModel',
        ),
    ]
